// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const City = sequelize.define('city', {
    cityId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(\'city_city_id_seq\'::regclass)'),
      allowNull: false,
    },
    city: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    lastUpdate: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
      allowNull: false,
    },
  }, {
    tableName: 'city',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  City.associate = (models) => {
    City.belongsTo(models.country, {
      foreignKey: {
        name: 'countryIdKey',
        field: 'country_id',
      },
      targetKey: 'countryId',
      as: 'country',
    });
    City.hasMany(models.address, {
      foreignKey: {
        name: 'cityIdKey',
        field: 'city_id',
      },
      sourceKey: 'cityId',
      as: 'addresses',
    });
  };

  return City;
};
