// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Payment = sequelize.define('payment', {
    paymentId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(\'payment_payment_id_seq\'::regclass)'),
      allowNull: false,
    },
    amount: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    paymentDate: {
      type: DataTypes.DATE,
      allowNull: false,
    },
  }, {
    tableName: 'payment',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Payment.associate = (models) => {
    Payment.belongsTo(models.customer, {
      foreignKey: {
        name: 'customerIdKey',
        field: 'customer_id',
      },
      targetKey: 'customerId',
      as: 'customer',
    });
    Payment.belongsTo(models.rental, {
      foreignKey: {
        name: 'rentalIdKey',
        field: 'rental_id',
      },
      targetKey: 'rentalId',
      as: 'rental',
    });
    Payment.belongsTo(models.staff, {
      foreignKey: {
        name: 'staffIdKey',
        field: 'staff_id',
      },
      targetKey: 'staffId',
      as: 'staff',
    });
  };

  return Payment;
};
