// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Staff = sequelize.define('staff', {
    staffId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(\'staff_staff_id_seq\'::regclass)'),
      allowNull: false,
    },
    firstName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
    },
    storeId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    active: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
      allowNull: false,
    },
    username: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    password: {
      type: DataTypes.STRING,
    },
    lastUpdate: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
      allowNull: false,
    },
  }, {
    tableName: 'staff',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Staff.associate = (models) => {
    Staff.belongsTo(models.address, {
      foreignKey: {
        name: 'addressIdKey',
        field: 'address_id',
      },
      targetKey: 'addressId',
      as: 'address',
    });
    Staff.hasMany(models.rental, {
      foreignKey: {
        name: 'staffIdKey',
        field: 'staff_id',
      },
      sourceKey: 'staffId',
      as: 'rentals',
    });
    Staff.hasMany(models.payment, {
      foreignKey: {
        name: 'staffIdKey',
        field: 'staff_id',
      },
      sourceKey: 'staffId',
      as: 'payments',
    });
    Staff.hasOne(models.store, {
      foreignKey: {
        name: 'managerStaffIdKey',
        field: 'manager_staff_id',
      },
      sourceKey: 'staffId',
      as: 'managerStaffStore',
    });
  };

  return Staff;
};
